# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
  #     desired widget in your `content/home/` folder.
  #   The weight parameter defines the order that the links will appear in.

main:
  - name: Acerca de mí
    url: /
    weight: 10
  - name: Experiencia
    url: experience/
    weight: 11
  - name: Eventos
    url: /#talks
    weight: 14
  - name: Publicaciones
    url: /#papers
    weight: 13
  - name: Proyectos
    url: projects/
    weight: 12
  #- name: Teaching
  #  url: teaching/
  #  weight: 40
